version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: enjoy-nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx

  redis:
    image: redis:6.2
    container_name: enjoy-redis
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis-data:/data

  mysql:
    image: mysql:8.0
    container_name: enjoy-mysql
    ports:
      - 3306:3306
    restart: always # 容器随docker启动自启
    privileged: true
    command:
      - --default-time-zone=+08:00
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      # MySQL:latest 已经弃用--default-authentication-plugin参数，使用MYSQL_AUTH_PLUGIN参数，才能够连接到数据库
      - MYSQL_AUTH_PLUGIN=caching_sha2_password
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql:ro
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql-data:/var/lib/mysql
    entrypoint: bash -c "chmod 644 /etc/mysql/my.cnf && exec /usr/local/bin/docker-entrypoint.sh mysqld"